In [ ]:
import numpy as np # we can treat lib as a module
#ndarray is one of the main class in numpy (np.ndarray(tuple of shape))

In [2]:
print(np.ndarray((3,2))) #tuple as a parameter    
#creating obj of ndarray directly
#not used and not recommended as the np.array and other function can create the obj of ndarray automatically 

[[2.52118789e-316 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [6.90830505e-310 6.90830398e-310]]


In [3]:
#np array from a lists
arr=np.array([1,2,3,4])
# The function np.array() creates and returns an instance of the ndarray class.
print(arr)

arr_2d=np.array([[1,2],[3,4]])
print(arr_2d)

[1 2 3 4]
[[1 2]
 [3 4]]


In [4]:
print(np.zeros((2,3)))
print("")
print(np.ones((3,2)))

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
print(np.arange(0,10,2)) # Array with a range of values np.arange(start,stop,step) and [stop] is not included

print(np.linspace(0,1,10)) # Array with 10 values linearly spaced between 0 and 1 np.linspace(start,stop,no. of intervals)

[0 2 4 6 8]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [6]:
x_arr=np.array([[1,2,3],[4,5,6]])
print(x_arr.shape)
y_arr=x_arr.reshape((3,2))
print(y_arr)
print(y_arr.shape)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
#here the random is sub module of numpy module
rand_arr=np.random.rand(2,3) #it is not taking tuple as parameter
print(rand_arr)

rand_int_arr=np.random.randint(1,10,(2,2))
print(rand_int_arr)

[[0.82269199 0.95997005 0.63706202]
 [0.96028986 0.02992644 0.7838944 ]]
[[6 8]
 [6 3]]
